### ISSUE TITLE
Rollup weirdness with imports and jsx

### ISSUE THREAD

**Issue by Bashkir15** [noirdoor/component#1]
Rollup doesn't seem to be playing nicely with React packages, both essential and otherwise. Switched to Webpack to move project along until more time can be spent resolving these issues

**Comment by sholladay** [comment]
Can you describe the issue you are having?

It's highly unlikely that Rollup is to blame, since its compilation process is pretty straightforward. More likely it is a problem in [Buble](https://gitlab.com/Rich-Harris/buble) related to code transformation. I suspect that switching to [Babel](https://github.com/rollup/rollup-plugin-babel) would fix it.

**Comment by Bashkir15** [comment]
That was what I gathered from reading on it afterwards. I switched to Babel and it seems to have resolved my issues for now +1:
